export const TYPES = {
  CLEAR_CART: 'CLEAR_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY'
}
